// SPDX-License-Identifier: AGPL-3.0-or-later

using Content.Client._Arcane.UserInterface.Systems.Actions.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.UserInterface.Systems.Actions.Widgets;

[GenerateTypedNameReferences]
public sealed partial class ActionsBar : UIWidget
{
    public readonly ActionsBarDragHandle DragHandle = new(); // Arcane

    public ActionsBar()
    {
        RobustXamlLoader.Load(this);

        // Arcane-Start
        ActionsContainer.Parent?.AddChild(DragHandle);
        DragHandle.SetPositionFirst();
        // Arcane-End
    }
}
