using Content.Client.Audio;
using Content.Shared._Arcane.CCVars;
using Content.Shared._Arcane.CVars;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Arcane.TTS;

[GenerateTypedNameReferences]
public sealed partial class TTSOptionsTab : Control
{
    public TTSOptionsTab()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        Control.AddOptionPercentSlider(
            ArtCVars.TTSVolume,
            SliderVolumeTTS,
            scale: ContentAudioSystem.TTSMultiplier);
        Control.AddOptionPercentSlider(
            ACCVars.TTSRadioVolume,
            SliderVolumeRadioTTS,
            scale: ContentAudioSystem.TTSRadioMultiplier);
        Control.AddOptionCheckBox(ACCVars.UseTTS, UseTTSCheckBox);

        Control.Initialize();
    }
}
