using Content.Client.UserInterface.Controls;
using Content.Shared._Arcane.TTS;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client._Arcane.TTS;

[GenerateTypedNameReferences]
public sealed partial class TTSVoiceChangeWindow : FancyWindow
{
    [Dependency] private IPrototypeManager _prototypeManager = default!;

    public Action<ProtoId<TTSVoicePrototype>>? VoiceSelected;

    public TTSVoiceChangeWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
    }

    public void PopulateVoices(IEnumerable<ProtoId<TTSVoicePrototype>> voices)
    {
        VoiceList.RemoveAllChildren();

        foreach (var voice in voices)
        {
            if (!_prototypeManager.TryIndex(voice, out var prototype))
                continue;

            var button = new Button
            {
                Text = Loc.GetString(prototype.Name),
                HorizontalExpand = true,
                HorizontalAlignment = HAlignment.Stretch,
                Margin = new Thickness(0, 4, 0, 0),
            };

            var voiceId = voice;
            button.OnPressed += _ => VoiceSelected?.Invoke(voiceId);

            VoiceList.AddChild(button);
        }
    }
}
