// SPDX-License-Identifier: AGPL-3.0-or-later

// Arcane-Edit-Start: Removed, replaced by the _Arcane surgery chart
//using Content.Client._Shitmed.Choice.UI;
//using Robust.Client.AutoGenerated;
//using Robust.Client.UserInterface.XAML;
//
//namespace Content.Client._Shitmed.Medical.Surgery;
//
//[GenerateTypedNameReferences]
//public sealed partial class SurgeryStepButton : ChoiceControl
//{
//    public EntityUid Step { get; set; }
//
//    public SurgeryStepButton()
//    {
//        RobustXamlLoader.Load(this);
//    }
//}
// Arcane-Edit-End
