// SPDX-License-Identifier: AGPL-3.0-or-later

// Arcane-Edit-Start: Removed, replaced by the _Arcane surgery chart
//using Robust.Client.AutoGenerated;
//using Robust.Client.UserInterface.CustomControls;
//using Robust.Client.UserInterface.XAML;
//
//namespace Content.Client._Shitmed.Medical.Surgery;
//
//[GenerateTypedNameReferences]
//public sealed partial class SurgeryWindow : DefaultWindow
//{
//    public SurgeryWindow()
//    {
//        RobustXamlLoader.Load(this);
//    }
//}
// Arcane-Edit-End
