- type: technology
  id: PlantAnalysis
  name: research-technology-plant-analysis-name
  description: research-technology-plant-analysis-desc
  icon:
    sprite: _CorvaxGoob/Objects/Specific/Hydroponics/plant_analyzer.rsi
    state: icon
  discipline: Service
  tier: 1
  startingTechnology: true
  pointCosts:
  - type: General
    amount: 500
  recipeUnlocks:
  - PlantAnalyzer
