// SPDX-License-Identifier: AGPL-3.0-or-later

using System.Numerics;
using Content.Client._Arcane.UserInterface.Systems.Actions;
using Content.Client.Stylesheets;
using Content.Client.UserInterface.Systems.Chat.Widgets;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.UserInterface.Screens;

[GenerateTypedNameReferences]
public sealed partial class SeparatedChatGameScreen : InGameScreen
{
    public const string StyleClassChatContainer = "ChatContainer";
    public const string StyleClassChatOutput = "ChatOutput";

    private readonly ActionsBarPlacement _actionsPlacement; // Arcane

    public SeparatedChatGameScreen()
    {
        RobustXamlLoader.Load(this);

        AutoscaleMaxResolution = new Vector2i(1080, 770);

        SetAnchorPreset(ScreenContainer, LayoutPreset.Wide);
        SetAnchorPreset(ViewportContainer, LayoutPreset.Wide);
        SetAnchorPreset(MainViewport, LayoutPreset.Wide);
        SetAnchorAndMarginPreset(Inventory, LayoutPreset.BottomLeft, margin: 5);
        SetAnchorAndMarginPreset(TopLeftContainer, LayoutPreset.TopLeft, margin: 10);
        SetAnchorAndMarginPreset(Ghost, LayoutPreset.BottomWide, margin: 80);
        SetAnchorAndMarginPreset(Hotbar, LayoutPreset.BottomWide, margin: 5);
        SetAnchorAndMarginPreset(Alerts, LayoutPreset.TopRight, margin: 10); // Goobstation Change
        SetAnchorAndMarginPreset(Targeting, LayoutPreset.BottomRight, margin: 5);

        ScreenContainer.OnSplitResizeFinished += () =>
            OnChatResized?.Invoke(new Vector2(ScreenContainer.SplitFraction, 0));

        ViewportContainer.OnResized += ResizeActionContainer;

        // Arcane-Start
        _actionsPlacement = new ActionsBarPlacement(Actions, () => new Vector2(10, 10));
        _actionsPlacement.LayoutChanged += UpdateVoteMenuOffset;
        Actions.OnVisibilityChanged += _ => UpdateVoteMenuOffset();
        _actionsPlacement.UpdateLayout();
        UpdateVoteMenuOffset();
        // Arcane-End
    }

    // Arcane-Start
    // Пока панель на месте по умолчанию, голосование стоит под ней
    private void UpdateVoteMenuOffset()
    {
        var offset = _actionsPlacement.IsCustom || !Actions.Visible ? 0 : Actions.Size.Y;
        SetMarginTop(TopLeftContainer, 10 + offset);
    }
    // Arcane-End

    private void ResizeActionContainer()
    {
        float indent = 20;
        Actions.ActionsContainer.MaxGridWidth = ViewportContainer.Size.X - indent;
    }

    public override ChatBox ChatBox => GetWidget<ChatBox>()!;

    public override void SetChatSize(Vector2 size)
    {
        ScreenContainer.ResizeMode = SplitContainer.SplitResizeMode.RespectChildrenMinSize;
    }
}