# SPDX-License-Identifier: AGPL-3.0-or-later
## See also ../roles.yml and ../spawners.yml

# Misc

### Visitors missing equipment for challenges
# CHALLENGE #
# these are specifically missing QOL equipment and have settings to make them harder.
# making changes to these should be done with care to avoid unbalancing challenging scenarios.

# Command
# Following use EventHumanoidMindShielded since they are heads and probably should have mindshields

- type: randomHumanoidSettings
  id: ChallengeVictimCaptain
  parent: EventHumanoidMindShielded
  randomizeName: false
  components:
    - type: GhostRole
      name: ghost-role-information-lost-challenge-commander-name
      description: ghost-role-information-lost-challenge-commander-description
      rules: ghost-role-information-lost-challenge-commander-rules
      raffle:
        settings: default
    - type: GhostTakeoverAvailable
    - type: Loadout
      prototypes: [ ChallengeVictimCaptain, ChallengeVictimCaptainAlt ] #!! This is supposed to be for challenge events. Its intentionally missing QOL gear to make interesting scenarios.
      roleLoadout: [ RoleSurvivalVoxSupport ]
    - type: RandomMetadata
      nameSegments:
      - NamesFirst
      - NamesLast
      nameFormat: name-format-standard

- type: randomHumanoidSettings
  id: ChallengeVictimChiefEngineer
  parent: EventHumanoidMindShielded
  randomizeName: false
  components:
    - type: GhostRole
      name: ghost-role-information-lost-challenge-commander-name
      description: ghost-role-information-lost-challenge-commander-description
      rules: ghost-role-information-lost-challenge-commander-rules
      raffle:
        settings: default
    - type: GhostTakeoverAvailable
    - type: Loadout
      prototypes: [ ChallengeVictimCE, ChallengeVictimCEAlt ] #!! This is supposed to be for challenge events. Its intentionally missing QOL gear to make interesting scenarios.
      roleLoadout: [ RoleSurvivalVoxSupport ]
    - type: RandomMetadata
      nameSegments:
      - NamesFirst
      - NamesLast
      nameFormat: name-format-standard

- type: randomHumanoidSettings
  id: ChallengeVictimCMO
  parent: EventHumanoidMindShielded
  randomizeName: false
  components:
    - type: GhostRole
      name: ghost-role-information-lost-challenge-commander-name
      description: ghost-role-information-lost-challenge-commander-description
      rules: ghost-role-information-lost-challenge-commander-rules
      raffle:
        settings: default
    - type: GhostTakeoverAvailable
    - type: Loadout
      prototypes: [ ChallengeVictimCMO, ChallengeVictimCMOAlt ] #!! This is supposed to be for challenge events. Its intentionally missing QOL gear to make interesting scenarios.
      roleLoadout: [ RoleSurvivalVoxSupport ]
    - type: RandomMetadata
      nameSegments:
      - NamesFirst
      - NamesLast
      nameFormat: name-format-standard

- type: randomHumanoidSettings
  id: ChallengeVictimHeadOfPersonnel
  parent: EventHumanoidMindShielded
  randomizeName: false
  components:
    - type: GhostRole
      name: ghost-role-information-lost-challenge-commander-name
      description: ghost-role-information-lost-challenge-commander-description
      rules: ghost-role-information-lost-challenge-commander-rules
      raffle:
        settings: default
    - type: GhostTakeoverAvailable
    - type: Loadout
      prototypes: [ ChallengeVictimHOP, ChallengeVictimHOPAlt ] #!! This is supposed to be for challenge events. Its intentionally missing QOL gear to make interesting scenarios.
      roleLoadout: [ RoleSurvivalVoxSupport ]
    - type: RandomMetadata
      nameSegments:
      - NamesFirst
      - NamesLast
      nameFormat: name-format-standard

- type: randomHumanoidSettings
  id: ChallengeVictimHeadOfSecurity
  parent: EventHumanoidMindShielded
  randomizeName: false
  components:
    - type: GhostRole
      name: ghost-role-information-lost-challenge-commander-name
      description: ghost-role-information-lost-challenge-commander-description
      rules: ghost-role-information-lost-challenge-commander-rules
      raffle:
        settings: default
    - type: GhostTakeoverAvailable
    - type: Loadout
      prototypes: [ ChallengeVictimHOS, ChallengeVictimHOSAlt ] #!! This is supposed to be for challenge events. Its intentionally missing QOL gear to make interesting scenarios.
      roleLoadout: [ RoleSurvivalVoxSupport ]
    - type: RandomMetadata
      nameSegments:
      - NamesFirst
      - NamesLast
      nameFormat: name-format-standard

- type: randomHumanoidSettings
  id: ChallengeVictimResearchDirector
  parent: EventHumanoidMindShielded
  randomizeName: false
  components:
    - type: GhostRole
      name: ghost-role-information-lost-challenge-commander-name
      description: ghost-role-information-lost-challenge-commander-description
      rules: ghost-role-information-lost-challenge-commander-rules
      raffle:
        settings: default
    - type: GhostTakeoverAvailable
    - type: Loadout
      prototypes: [ ChallengeVictimRD, ChallengeVictimRDAlt ] #!! This is supposed to be for challenge events. Its intentionally missing QOL gear to make interesting scenarios.
      roleLoadout: [ RoleSurvivalVoxSupport ]
    - type: RandomMetadata
      nameSegments:
      - NamesFirst
      - NamesLast
      nameFormat: name-format-standard

- type: randomHumanoidSettings
  id: ChallengeVictimQuartermaster
  parent: EventHumanoidMindShielded
  randomizeName: false
  components:
    - type: GhostRole
      name: ghost-role-information-lost-challenge-commander-name
      description: ghost-role-information-lost-challenge-commander-description
      rules: ghost-role-information-lost-challenge-commander-rules
      raffle:
        settings: default
    - type: GhostTakeoverAvailable
    - type: Loadout
      prototypes: [ ChallengeVictimQM, ChallengeVictimQMAlt ] #!! This is supposed to be for challenge events. Its intentionally missing QOL gear to make interesting scenarios.
      roleLoadout: [ RoleSurvivalVoxSupport ]
    - type: RandomMetadata
      nameSegments:
      - NamesFirst
      - NamesLast
      nameFormat: name-format-standard

# Security
# Following use EventHumanoidMindShielded since they are heads and probably should have mindshields

# Cargo

- type: randomHumanoidSettings
  id: ChallengeCargoTechnician
  randomizeName: false
  components:
    - type: GhostRole
      name: ghost-role-information-lost-challenge-cargo-technican-name
      description: ghost-role-information-lost-challenge-cargo-technican-description
      rules: ghost-role-information-lost-disaster-challenge-cargo-technican-rules
      raffle:
        settings: short
    - type: GhostTakeoverAvailable
    - type: Loadout
      prototypes: [ ChallengeCargoTechGearSuit, ChallengeCargoTechGearCoat ] #!! This is supposed to be for challenge events. Its intentionally missing QOL gear to make interesting scenarios.
      roleLoadout: [ RoleSurvivalVoxSupport ]
    - type: RandomMetadata
      nameSegments:
      - NamesFirst
      - NamesLast
      nameFormat: name-format-standard

# Engineering

# Medical

# Science

# Civilian

# Misc

### Syndicate & Hostiles

- type: randomHumanoidSettings
  id: SyndieSoldierTeamLeader
  parent: EventHumanoid
  components:
    - type: NpcFactionMember
      factions:
      - Syndicate
    - type: NukeOperative
    - type: GhostRole
      name: ghost-role-information-syndie-soldier-teamlead-name
      description: ghost-role-information-syndie-soldier-teamlead-description
      rules: ghost-role-information-rules-team-antagonist
      mindRoles:
      - MindRoleGhostRoleTeamAntagonist
      raffle:
        settings: default
    - type: Loadout
      prototypes: [ SyndicateFootsoldierTeamLeaderGear ]
      roleLoadout: [ RoleSurvivalSyndicate ]

- type: randomHumanoidSettings
  id: SyndieSoldier
  parent: EventHumanoid
  components:
    - type: NpcFactionMember
      factions:
      - Syndicate
    - type: NukeOperative
    - type: GhostRole
      name: ghost-role-information-syndie-soldier-name
      description: ghost-role-information-syndie-soldier-description
      rules: ghost-role-information-rules-team-antagonist
      mindRoles:
      - MindRoleGhostRoleTeamAntagonist
      raffle:
        settings: default
    - type: Loadout
      prototypes: [ SyndicateFootsoldierGear ]
      roleLoadout: [ RoleSurvivalSyndicate ]

- type: randomHumanoidSettings
  id: SyndieVisitor
  parent: EventHumanoid
  components:
    - type: NpcFactionMember
      factions:
      - Syndicate
    - type: GhostRole
      name: ghost-role-information-syndie-disaster-victim-name
      description: ghost-role-information-syndie-disaster-victim-description
      rules: ghost-role-information-nonantagonist-rules
      raffle:
        settings: short
    - type: Loadout
      prototypes: [ SyndicateOperativeGearCivilian ]
      roleLoadout: [ RoleSurvivalSyndicate ]

- type: randomHumanoidSettings
  id: PirateScooner
  parent: EventHumanoid
  components:
    - type: NpcFactionMember
      factions:
      - Syndicate
    - type: GhostRole
      name: ghost-role-information-pirate-name
      description: ghost-role-information-pirate-description
      rules: ghost-role-information-rules-team-antagonist
      mindRoles:
      - MindRoleGhostRoleTeamAntagonist
      raffle:
        settings: default
    - type: Loadout
      prototypes: [ PirateScoonerAltA, PirateScoonerAltB, PirateScoonerAltC, PirateScoonerAltD ]
      roleLoadout: [ RoleSurvivalEVA ]

- type: randomHumanoidSettings
  id: PirateCaptainScooner
  parent: EventHumanoid
  components:
    - type: NpcFactionMember
      factions:
      - Syndicate
    - type: GhostRole
      name: ghost-role-information-pirate-captain-name
      description: ghost-role-information-pirate-captain-description
      rules: ghost-role-information-rules-team-antagonist
      mindRoles:
      - MindRoleGhostRoleTeamAntagonist
      raffle:
        settings: default
    - type: Loadout
      prototypes: [ PirateCaptainScooner ]
      roleLoadout: [ RoleSurvivalEVA ]

### Other

- type: randomHumanoidSettings
  id: VisitorBlackmarketeer
  parent: EventHumanoid
  components:
    - type: GhostRole
      name: ghost-role-information-blackmarketeer-name
      description: ghost-role-information-blackmarketeer-description
      rules: ghost-role-information-freeagent-rules
      mindRoles:
      - MindRoleGhostRoleFreeAgent
      raffle:
        settings: default
    - type: Loadout
      prototypes: [ VisitorBlackmarketeer, VisitorBlackmarketeer ]
      roleLoadout: [ RoleSurvivalStandard ]

- type: randomHumanoidSettings
  id: Cossack
  parent: EventHumanoid
  components:
    - type: RussianAccent
    - type: ScrambledAccent
    - type: SlurredAccent
    - type: SouthernAccent
    - type: GhostRole
      name: ghost-role-information-cossack-name
      description: ghost-role-information-cossack-description
      rules: ghost-role-information-freeagent-rules
      mindRoles:
      - MindRoleGhostRoleFreeAgent
      raffle:
        settings: default
    - type: Loadout
      prototypes: [ CossackGear ]
      roleLoadout: [ RoleSurvivalEVA ]
