using System.Numerics;
using Content.Client.UserInterface.Controls;
using Content.Shared._Arcane.InclothingTools;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Arcane.InclothingTools;

[GenerateTypedNameReferences]
public sealed partial class InclothingToolsRadialMenu : RadialMenu
{
    [Dependency] private readonly EntityManager _entityManager = default!;

    public event Action<EntityUid>? SendSelectToolMessageAction;

    public event Action? SendUnequipToolMessageAction;


    public EntityUid Entity { get; set; }

    public InclothingToolsRadialMenu()
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);
    }

    public void SetEntity(EntityUid entity)
    {
        Entity = entity;
        RefreshUi();
    }

    public void RefreshUi()
    {
        var main = FindControl<RadialContainer>("Main");

        if (!_entityManager.TryGetComponent<InclothingToolsComponent>(Entity, out var tools))
            return;

        var toolsContainer = tools.Container;

        if (toolsContainer == null)
            return;

        string tooltip;
        var tooltipEquip = Loc.GetString("inclothing-tools-tooltip-equip");
        var tooltipUnequip = Loc.GetString("inclothing-tools-tooltip-unequip");

        foreach (var attached in tools.ToolsUids)
        {
            if (toolsContainer.Contains(attached))
                tooltip = tooltipEquip;
            else
                tooltip = tooltipUnequip;

            var button = new InclothingToolsRadialMenuButton
            {
                SetSize = new Vector2(64, 64),
                ToolTip = tooltip,
                AttachedToolId = attached
            };

            var spriteView = new SpriteView
            {
                SetSize = new Vector2(48, 48),
                VerticalAlignment = VAlignment.Center,
                HorizontalAlignment = HAlignment.Center,
                Stretch = SpriteView.StretchMode.Fill
            };

            spriteView.SetEntity(attached);

            button.AddChild(spriteView);
            main.AddChild(button);
        }

        var emptyButton = new RadialMenuButtonWithSector
        {
            SetSize = new Vector2(64, 64),
            ToolTip = Loc.GetString("inclothing-tools-tooltip-unequip-all")
        };

        var emptySpriteView = new SpriteView
        {
            SetSize = new Vector2(48, 48)
        };

        emptyButton.AddChild(emptySpriteView);
        main.AddChild(emptyButton);

        AddActionOnClick(main);
    }

    private void AddActionOnClick(RadialContainer main)
    {
        foreach (var child in main.Children)
        {
            var castChild = child as InclothingToolsRadialMenuButton;

            if (castChild == null)
            {
                if (child is not RadialMenuButtonWithSector emptyButton)
                    continue;

                emptyButton.OnPressed += _ =>
                {
                    SendUnequipToolMessageAction?.Invoke();
                    Close();
                };
                continue;
            }

            castChild.OnPressed += _ =>
            {
                SendSelectToolMessageAction?.Invoke(castChild.AttachedToolId);
                Close();
            };
        }
    }

}

public sealed class InclothingToolsRadialMenuButton : RadialMenuButtonWithSector
{
    public EntityUid AttachedToolId { get; set; }
}