using System.Numerics;
using Content.Client.UserInterface.Controls;
using Content.Shared._Arcane.InclothingTools;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Arcane.InclothingTools;

[GenerateTypedNameReferences]
public sealed partial class InclothingToolsRadialMenu : RadialMenu
{
    [Dependency] private readonly EntityManager _entityManager = default!;

    public event Action<EntityUid>? SendSelectToolMessageAction;

    public EntityUid Entity { get; set; }

    public InclothingToolsRadialMenu()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);
    }

    public void SetEntity(EntityUid entity)
    {
        Entity = entity;
        RefreshUi();
        SendSelectToolMessageAction?.Invoke(entity);
    }

    public void RefreshUi()
    {
        var main = FindControl<RadialContainer>("Main");

        if (!_entityManager.TryGetComponent<InclothingToolsComponent>(Entity, out var tools))
            return;

        var toolsContainer = tools.Container;

        if (toolsContainer == null)
            return;

        string tooltip = string.Empty;

        foreach (var attached in tools.ToolsUids)
        {
            if (toolsContainer.Contains(attached))
                tooltip = "Test Inside Container";
            else
                tooltip = "Test Outside Container";

            var button = new InclothingToolsRadialMenuButton
            {
                SetSize = new Vector2(64, 64),
                ToolTip = tooltip,
                AttachedToolId = attached
            };

            var spriteView = new SpriteView
            {
                SetSize = new Vector2(48, 48),
                VerticalAlignment = VAlignment.Center,
                HorizontalAlignment = HAlignment.Center,
                Stretch = SpriteView.StretchMode.Fill
            };

            spriteView.SetEntity(attached);

            button.AddChild(spriteView);
            main.AddChild(button);
        }

        AddActionOnClick(main);
    }

    private void AddActionOnClick(RadialContainer main)
    {
        foreach (var child in main.Children)
        {
            if (child is not InclothingToolsRadialMenuButton castChild)
                return;

            castChild.OnPressed += _ =>
            {
                SendSelectToolMessageAction?.Invoke(castChild.AttachedToolId);
                main.DisposeAllChildren();
                RefreshUi();
            };
        }
    }

}

public sealed class InclothingToolsRadialMenuButton : RadialMenuButtonWithSector
{
    public EntityUid AttachedToolId { get; set; }
}