using System.Linq;
using System.Numerics;
using Content.Client._Arcane.StyleSheets;
using Content.Shared._Arcane.DiscordRoles;
using Content.Shared._Arcane.Ghost;
using Content.Shared._Orion.CustomGhost;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client._Arcane.Sponsor.UI;

[GenerateTypedNameReferences]
public sealed partial class SponsorInfoWindow : DefaultWindow
{
    [Dependency] private readonly IPrototypeManager _prototypes = default!;
    [Dependency] private readonly IEntityManager _entities = default!;
    [Dependency] private readonly IEntitySystemManager _systems = default!;

    private readonly List<EntityUid> _previewEntities = [];

    public SponsorInfoWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        Tabs.SetTabTitle(0, Loc.GetString("arcane-sponsor-tab-benefits"));
        Tabs.SetTabTitle(1, Loc.GetString("arcane-sponsor-tab-ghosts"));
        Tabs.SetTabTitle(2, Loc.GetString("arcane-sponsor-tab-themes"));
        OnClose += DeletePreviews;

        PopulateGhosts();
        PopulateThemes();
    }

    private void PopulateGhosts()
    {
        var sprite = _systems.GetEntitySystem<SpriteSystem>();
        var ghosts = _prototypes.EnumeratePrototypes<CustomGhostPrototype>()
            .Where(ghost => !ghost.Abstract &&
                            ghost.Restrictions?.Any(restriction => restriction is SponsorGhostRestriction) == true)
            .OrderBy(ghost => ghost.DisplayName);

        BoxContainer? row = null;
        var count = 0;
        foreach (var ghost in ghosts)
        {
            if (count++ % 4 == 0)
            {
                row = new BoxContainer
                {
                    Orientation = BoxContainer.LayoutOrientation.Horizontal,
                    HorizontalAlignment = HAlignment.Center,
                    SeparationOverride = 6,
                };
                GhostRows.AddChild(row);
            }

            var preview = _entities.Spawn(ghost.GhostEntityPrototype);
            _previewEntities.Add(preview);
            sprite.ForceUpdate(preview);
            sprite.SetVisible(preview, true);

            var card = new PanelContainer
            {
                StyleClasses = { ArcaneStyleClass.LobbySurface },
                SetWidth = 132,
            };
            var contents = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Vertical,
                SeparationOverride = 2,
                MinWidth = 120,
                Margin = new Thickness(4),
            };
            var spriteView = new SpriteView
            {
                SetSize = new Vector2(48, 48),
                HorizontalAlignment = HAlignment.Center,
                Stretch = SpriteView.StretchMode.Fill,
            };
            spriteView.SetEntity(preview);
            contents.AddChild(spriteView);
            contents.AddChild(new Label
            {
                Text = ghost.DisplayName,
                FontColorOverride = Color.FromHex("#DCE5E9"),
                HorizontalAlignment = HAlignment.Center,
            });
            card.ToolTip = $"{ghost.DisplayName}\n{ghost.DisplayDesc}";
            card.AddChild(contents);
            row!.AddChild(card);
        }
    }

    private void PopulateThemes()
    {
        foreach (var theme in ArcanePalette.Themes.Where(theme => theme.RequiredRole == DiscordRole.SponsorTier2))
        {
            var card = new PanelContainer
            {
                PanelOverride = new StyleBoxFlat
                {
                    BackgroundColor = theme.Primary.Background,
                    BorderColor = theme.Accent,
                    BorderThickness = new Thickness(1),
                },
            };
            var contents = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Vertical,
                Margin = new Thickness(10),
                SeparationOverride = 5,
            };
            contents.AddChild(new Label
            {
                Text = Loc.GetString(theme.NameLocId),
                FontColorOverride = theme.Primary.Text,
                StyleClasses = { "LabelHeadingBigger" },
            });
            contents.AddChild(new Label
            {
                Text = Loc.GetString("arcane-sponsor-theme-sample-text"),
                FontColorOverride = theme.Primary.TextDark,
            });

            var sampleButton = new PanelContainer
            {
                PanelOverride = new StyleBoxFlat
                {
                    BackgroundColor = theme.Buttons.Element,
                    BorderColor = theme.Buttons.Base,
                    BorderThickness = new Thickness(1),
                },
            };
            sampleButton.AddChild(new Label
            {
                Text = Loc.GetString("arcane-sponsor-theme-sample-button"),
                FontColorOverride = theme.Buttons.Text,
                Margin = new Thickness(8, 4),
            });
            contents.AddChild(sampleButton);
            card.AddChild(contents);
            ThemeList.AddChild(card);
        }
    }

    private void DeletePreviews()
    {
        foreach (var entity in _previewEntities)
            _entities.TryQueueDeleteEntity(entity);

        _previewEntities.Clear();
    }
}
