using System.Numerics;
using Content.Client.Stylesheets;
using Content.Shared._Arcane.Surgery;
using Robust.Client.AutoGenerated;
using Robust.Client.Input;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Arcane.Medical.Surgery;

public readonly record struct SurgeryToolOptionEntry(SurgeryToolOption Option, string Name, string Details);

/// <summary>
/// Lists the steps a tool click could perform, next to the cursor.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class SurgeryToolOptionsPopup : Popup
{
    [Dependency] private readonly IInputManager _input = default!;

    public event Action<SurgeryToolOption>? OnPicked;

    public SurgeryToolOptionsPopup()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
    }

    public void Populate(string title, IEnumerable<SurgeryToolOptionEntry> entries)
    {
        TitleLabel.Text = title;
        Options.DisposeAllChildren();

        foreach (var entry in entries)
        {
            var button = new Button { StyleClasses = { StyleClass.ButtonOpenBoth } };
            var labels = new BoxContainer { Orientation = BoxContainer.LayoutOrientation.Vertical, Margin = new Thickness(4, 2) };
            labels.AddChild(new Label { Text = entry.Name });
            labels.AddChild(new Label { Text = entry.Details, StyleClasses = { StyleClass.LabelSubText } });
            button.AddChild(labels);

            var option = entry.Option;
            button.OnPressed += _ =>
            {
                Close();
                OnPicked?.Invoke(option);
            };
            Options.AddChild(button);
        }
    }

    public void OpenAtMouse()
    {
        Open(UIBox2.FromDimensions(_input.MouseScreenPosition.Position / UIScale, Vector2.Zero));
    }
}
