using System.Linq;
using System.Numerics;
using Content.Client._Arcane.StyleSheets;
using Content.Client.Stylesheets;
using Content.Client.Stylesheets.Palette;
using Content.Client.Stylesheets.Stylesheets;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Timing;

namespace Content.Client._Arcane.Medical.Surgery;

public enum SurgeryStepStatus : byte
{
    Locked,
    Next,
    Active,
    Complete,
    // The step's check already passes, but earlier steps are still pending, so it may be needed later.
    Satisfied,
}

public readonly record struct SurgeryStepData(
    EntProtoId Surgery,
    EntProtoId Step,
    EntityUid StepEnt,
    string Name,
    SurgeryStepStatus Status,
    string? Warning,
    bool CanPerform,
    TimeSpan ActiveStart,
    TimeSpan ActiveDuration);

public sealed record SurgeryStepSection(EntProtoId Id, string Name, bool Complete, List<SurgeryStepData> Steps);

/// <summary>
/// Step tool icon drawn with the stylesheet button textures, tinted by the step status.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class SurgeryStepIcon : ContainerButton
{
    [Dependency] private readonly IGameTiming _timing = default!;
    [Dependency] private readonly IStylesheetManager _stylesheets = default!;
    [Dependency] private readonly IResourceCache _resourceCache = default!;

    private const float IconSize = 32f;
    private const float Padding = 8f;

    private readonly Texture _texture;
    private readonly Texture _borderedTexture;
    private readonly StyleBoxTexture _box = new();

    public SurgeryStepData Data { get; private set; }

    public SurgeryStepIcon()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _texture = _resourceCache.GetResource<TextureResource>(NanotrasenStylesheet.TextureRoot / "button.svg.96dpi.png");
        _borderedTexture = _resourceCache.GetResource<TextureResource>(ArcaneStylesheet.TextureRoot / "button_bordered.svg.96dpi.png");
        _box.SetPatchMargin(StyleBox.Margin.All, 10);

        Icon.SetSize = new Vector2(IconSize);
        Icon.Margin = new Thickness(Padding);
    }

    /// <summary>
    /// A selectable icon stays pressable even when its step cannot be performed, so it can open its operation.
    /// </summary>
    public void Set(SurgeryStepData data, Texture? icon, bool selectable)
    {
        Data = data;
        var status = data.Status;
        var clickable = selectable || status == SurgeryStepStatus.Next && data.CanPerform;

        Disabled = !clickable;
        DefaultCursorShape = clickable ? CursorShape.Hand : CursorShape.Arrow;

        Icon.Texture = icon;
        Icon.Modulate = status is SurgeryStepStatus.Complete or SurgeryStepStatus.Satisfied
            ? Color.White.WithAlpha(0.5f)
            : Color.White;

        CheckLabel.Visible = status is SurgeryStepStatus.Complete or SurgeryStepStatus.Satisfied;
        CheckLabel.SetOnlyStyleClass(status == SurgeryStepStatus.Satisfied ? StyleClass.StatusWarning : StyleClass.StatusGood);

        var tooltip = data.Name;
        if (status == SurgeryStepStatus.Next && !string.IsNullOrEmpty(data.Warning))
            tooltip += "\n" + data.Warning;
        else if (status == SurgeryStepStatus.Satisfied)
            tooltip += "\n" + Loc.GetString("surgery-ui-step-satisfied-tooltip");

        ToolTip = tooltip;
    }

    protected override void Draw(DrawingHandleScreen handle)
    {
        base.Draw(handle);

        var theme = ArcanePalette.Themes.First(t => t.Id == _stylesheets.CurrentTheme);
        var status = Data.Status;
        var hovered = DrawMode == DrawModeEnum.Hover;
        var pressed = DrawMode == DrawModeEnum.Pressed;

        // Mirrors the stylesheet buttons: a plain fill when idle, the bordered texture tinted by the state color otherwise.
        Color? outline = status switch
        {
            SurgeryStepStatus.Active => theme.Highlight.Base,
            SurgeryStepStatus.Next when !string.IsNullOrEmpty(Data.Warning) => Palettes.Status.Warning,
            SurgeryStepStatus.Next => hovered ? theme.Highlight.Text : theme.Highlight.Base,
            SurgeryStepStatus.Complete => Palettes.Status.Good.WithAlpha(0.7f),
            SurgeryStepStatus.Satisfied => Palettes.Status.Warning.WithAlpha(0.7f),
            _ when hovered || pressed => theme.Highlight.Base,
            _ => null,
        };

        if (outline is { } color)
        {
            _box.Texture = _borderedTexture;
            _box.Modulate = pressed ? color.WithAlpha(color.A * 0.82f) : color;
        }
        else
        {
            _box.Texture = _texture;
            _box.Modulate = Disabled ? theme.Buttons.DisabledElement : theme.Buttons.Element;
        }

        _box.Draw(handle, PixelSizeBox, UIScale);

        if (status != SurgeryStepStatus.Active)
            return;

        var fraction = Data.ActiveDuration > TimeSpan.Zero
            ? Math.Clamp((float) ((_timing.CurTime - Data.ActiveStart) / Data.ActiveDuration), 0f, 1f)
            : 1f;

        // A bar in the bottom padding, clear of the cut corner and the icon.
        var left = Padding * UIScale;
        var width = PixelWidth - left * 2;
        var top = PixelHeight - (Padding - 2f) * UIScale;
        handle.DrawRect(new UIBox2(left, top, left + width, top + 3f * UIScale), theme.Highlight.Element);
        handle.DrawRect(new UIBox2(left, top, left + width * fraction, top + 3f * UIScale), Palettes.Status.Good);
    }
}
