using Content.Client.Stylesheets;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client._Arcane.Medical.Surgery;

public enum SurgeryOperationGroup : byte
{
    Started,
    Available,
    NeedsPreparation,
    Closing,
    Completed,
}

public sealed record SurgeryOperationEntry(
    EntProtoId Id,
    string Name,
    SurgeryOperationGroup Group,
    int Done,
    int Total,
    List<SurgeryStepData> Steps);

[GenerateTypedNameReferences]
public sealed partial class SurgeryOperationRow : BoxContainer
{
    private readonly List<SurgeryStepIcon> _icons = new();
    private readonly List<Label> _sectionLabels = new();
    private int? _layout;

    public event Action? OnHeaderPressed;

    public SurgeryOperationRow()
    {
        RobustXamlLoader.Load(this);
        Header.OnPressed += _ => OnHeaderPressed?.Invoke();
    }

    /// <summary>
    /// Shows the operation header and its step icons; an expanded row lists every section of its requirement chain.
    /// The header stays pressed while the operation is the surgeon's plan.
    /// </summary>
    public void Set(SurgeryOperationEntry entry,
        IReadOnlyList<SurgeryStepSection> sections,
        bool expanded,
        bool planned,
        Func<EntityUid, Texture?> getIcon)
    {
        Header.Pressed = planned;
        Stripe.PanelOverride = new StyleBoxFlat(GetGroupColor(entry.Group));
        ArrowLabel.Text = expanded ? "▼" : "▶";

        NameLabel.Text = entry.Name;
        NameLabel.SetOnlyStyleClass(entry.Group is SurgeryOperationGroup.NeedsPreparation or SurgeryOperationGroup.Completed
            ? StyleClass.LabelWeak
            : StyleClass.LabelKeyText);

        if (entry.Group == SurgeryOperationGroup.Completed)
        {
            StatusLabel.Text = "✓";
            StatusLabel.SetOnlyStyleClass(StyleClass.StatusGood);
        }
        else if (entry.Done > 0 && entry.Group != SurgeryOperationGroup.NeedsPreparation)
        {
            StatusLabel.Text = $"{entry.Done}/{entry.Total}";
            StatusLabel.SetOnlyStyleClass(StyleClass.StatusWarning);
        }
        else
        {
            StatusLabel.Text = string.Empty;
        }

        // Controls are reused while the layout stays the same, so a refresh does not reset hover or tooltips.
        var layout = new HashCode();
        layout.Add(expanded);
        foreach (var section in sections)
        {
            layout.Add(section.Id);
            layout.Add(section.Steps.Count);
        }

        if (_layout != layout.ToHashCode())
        {
            _layout = layout.ToHashCode();
            BuildSteps(sections);
        }

        var icon = 0;
        for (var i = 0; i < sections.Count; i++)
        {
            var section = sections[i];
            if (sections.Count > 1)
            {
                _sectionLabels[i].Text = section.Complete ? $"✓ {section.Name}" : section.Name;
                _sectionLabels[i].SetOnlyStyleClass(section.Complete ? StyleClass.StatusGood : StyleClass.LabelSubText);
            }

            foreach (var step in section.Steps)
            {
                _icons[icon++].Set(step, getIcon(step.StepEnt), !expanded);
            }
        }
    }

    private void BuildSteps(IReadOnlyList<SurgeryStepSection> sections)
    {
        Steps.DisposeAllChildren();
        _icons.Clear();
        _sectionLabels.Clear();

        foreach (var section in sections)
        {
            if (sections.Count > 1)
            {
                var label = new Label();
                _sectionLabels.Add(label);
                Steps.AddChild(label);
            }

            if (section.Steps.Count == 0)
                continue;

            var chain = new WrapContainer { SeparationOverride = 4, CrossSeparationOverride = 4 };
            for (var i = 0; i < section.Steps.Count; i++)
            {
                if (i > 0)
                {
                    chain.AddChild(new Label
                    {
                        Text = "→",
                        VerticalAlignment = VAlignment.Center,
                        StyleClasses = { StyleClass.LabelWeak },
                    });
                }

                var icon = new SurgeryStepIcon();
                icon.OnPressed += _ => OnHeaderPressed?.Invoke();
                _icons.Add(icon);
                chain.AddChild(icon);
            }

            Steps.AddChild(chain);
        }

        Steps.Visible = Steps.ChildCount > 0;
    }

    private static Color GetGroupColor(SurgeryOperationGroup group)
    {
        return group switch
        {
            SurgeryOperationGroup.Started => Color.FromHex("#E0A93F"),
            SurgeryOperationGroup.Available => Color.FromHex("#5FBF6A"),
            SurgeryOperationGroup.Closing => Color.FromHex("#4FA3E0"),
            SurgeryOperationGroup.Completed => Color.FromHex("#3E6B47"),
            _ => Color.FromHex("#55555F"),
        };
    }
}
