using Content.Client.Stylesheets;
using Content.Client.Stylesheets.Palette;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Timing;
using Robust.Shared.Utility;

namespace Content.Client._Arcane.Medical.Surgery;

public enum SurgeryStepStatus : byte
{
    Locked,
    Next,
    Active,
    Complete,
}

public readonly record struct SurgeryStepData(
    EntProtoId Surgery,
    EntProtoId Step,
    EntityUid StepEnt,
    int Number,
    string Name,
    SurgeryStepStatus Status,
    string? Warning,
    bool CanPerform,
    TimeSpan ActiveStart,
    TimeSpan ActiveDuration);

public sealed record SurgeryStepSection(EntProtoId Id, string Name, bool Complete, int Done, int Total, List<SurgeryStepData> Steps);

[GenerateTypedNameReferences]
public sealed partial class SurgeryStepRow : ContainerButton
{
    [Dependency] private readonly IGameTiming _timing = default!;
    [Dependency] private readonly IResourceCache _cache = default!;

    private const int NameFontSize = 14;
    private static readonly Color ActiveBackground = Palettes.Status.Good.WithAlpha(0.08f);
    private static readonly Color ActiveFill = Palettes.Status.Good.WithAlpha(0.25f);

    public SurgeryStepData Data { get; private set; }

    public SurgeryStepRow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
    }

    public void Set(SurgeryStepData data, Texture? icon)
    {
        Data = data;
        var status = data.Status;
        var highlighted = status is SurgeryStepStatus.Next or SurgeryStepStatus.Active;
        var clickable = status == SurgeryStepStatus.Next;

        // Only the next step looks and acts like a button; the other rows are plain text.
        SetStyleClass(StyleClassButton, clickable);
        SetStyleClass(StyleClass.ButtonOpenBoth, clickable);
        SetStyleClass(StyleClass.Positive, clickable);
        Disabled = !clickable || !data.CanPerform;
        DefaultCursorShape = clickable && data.CanPerform ? CursorShape.Hand : CursorShape.Arrow;

        NumberLabel.Text = status == SurgeryStepStatus.Complete ? "✓" : data.Number.ToString();
        NumberLabel.SetOnlyStyleClass(status switch
        {
            SurgeryStepStatus.Complete => StyleClass.StatusGood,
            SurgeryStepStatus.Locked => StyleClass.LabelWeak,
            _ => StyleClass.LabelKeyText,
        });

        NameLabel.Text = data.Name;
        NameLabel.FontOverride = _cache.NotoStack(highlighted ? "Bold" : "Regular", NameFontSize);
        NameLabel.SetOnlyStyleClass(highlighted ? StyleClass.LabelKeyText : StyleClass.LabelWeak);

        Icon.Texture = icon;
        Icon.Modulate = highlighted ? Color.White : Color.White.WithAlpha(0.5f);

        WarningLabel.Visible = clickable && !string.IsNullOrEmpty(data.Warning);
        if (WarningLabel.Visible)
            WarningLabel.SetMessage(FormattedMessage.FromUnformatted(data.Warning!), Palettes.Status.Warning);

        ActiveLabel.Visible = status == SurgeryStepStatus.Active;
    }

    protected override void Draw(DrawingHandleScreen handle)
    {
        base.Draw(handle);

        if (Data.Status != SurgeryStepStatus.Active)
            return;

        var fraction = Data.ActiveDuration > TimeSpan.Zero
            ? Math.Clamp((float) ((_timing.CurTime - Data.ActiveStart) / Data.ActiveDuration), 0f, 1f)
            : 1f;

        var box = PixelSizeBox;
        handle.DrawRect(box, ActiveBackground);
        handle.DrawRect(new UIBox2(box.Left, box.Top, box.Left + box.Width * fraction, box.Bottom), ActiveFill);
    }

    private void SetStyleClass(string styleClass, bool enabled)
    {
        if (enabled)
            AddStyleClass(styleClass);
        else
            RemoveStyleClass(styleClass);
    }
}
