using System.Linq;
using System.Numerics;
using Content.Client._Arcane.StyleSheets;
using Content.Client.Stylesheets;
using Content.Client.Stylesheets.Palette;
using Content.Client.Stylesheets.Stylesheets;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;

namespace Content.Client._Arcane.Medical.Surgery;

public enum SurgeryStepStatus : byte
{
    Locked,
    Next,
    Active,
    Complete,
    // The step's check already passes, but earlier steps are still pending, so it may be needed later.
    Satisfied,
}

public readonly record struct SurgeryStepData(
    EntityUid StepEnt,
    string Name,
    // The required surgery the step belongs to, when it is not the operation itself.
    string? Stage,
    SurgeryStepStatus Status,
    string? Tool,
    string? Warning,
    TimeSpan ActiveStart,
    TimeSpan ActiveDuration);

/// <summary>
/// Step tool icon drawn with the stylesheet button textures, tinted by the step status.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class SurgeryStepIcon : ContainerButton
{
    [Dependency] private readonly IGameTiming _timing = default!;
    [Dependency] private readonly IStylesheetManager _stylesheets = default!;
    [Dependency] private readonly IResourceCache _resourceCache = default!;

    private const float IconSize = 32f;
    private const float Padding = 8f;

    private readonly Texture _texture;
    private readonly Texture _borderedTexture;
    private readonly StyleBoxTexture _box = new();

    private SurgeryStepData _data;

    public SurgeryStepIcon()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _texture = _resourceCache.GetResource<TextureResource>(NanotrasenStylesheet.TextureRoot / "button.svg.96dpi.png");
        _borderedTexture = _resourceCache.GetResource<TextureResource>(ArcaneStylesheet.TextureRoot / "button_bordered.svg.96dpi.png");
        _box.SetPatchMargin(StyleBox.Margin.All, 10);

        Icon.SetSize = new Vector2(IconSize);
        Icon.Margin = new Thickness(Padding);
        // Steps are done with tools on the patient, so the icon only shows the step.
        Disabled = true;
    }

    public void Set(SurgeryStepData data, Texture? icon)
    {
        _data = data;
        var status = data.Status;

        Icon.Texture = icon;
        Icon.Modulate = status == SurgeryStepStatus.Complete ? Color.White.WithAlpha(0.5f) : Color.White;
        CheckLabel.Visible = status == SurgeryStepStatus.Complete;

        var tooltip = data.Name;
        if (data.Stage != null)
            tooltip += "\n" + Loc.GetString("surgery-ui-step-stage", ("stage", data.Stage));

        if (data.Tool != null)
            tooltip += "\n" + Loc.GetString("surgery-ui-step-tool", ("tool", data.Tool));

        if (status == SurgeryStepStatus.Next && !string.IsNullOrEmpty(data.Warning))
            tooltip += "\n" + data.Warning;
        else if (status == SurgeryStepStatus.Satisfied)
            tooltip += "\n" + Loc.GetString("surgery-ui-step-satisfied-tooltip");

        ToolTip = tooltip;
    }

    protected override void Draw(DrawingHandleScreen handle)
    {
        base.Draw(handle);

        var theme = ArcanePalette.Themes.First(t => t.Id == _stylesheets.CurrentTheme);
        var status = _data.Status;

        // Mirrors the stylesheet buttons: a plain fill when idle, the bordered texture tinted by the state color otherwise.
        Color? outline = status switch
        {
            SurgeryStepStatus.Active => theme.Highlight.Base,
            SurgeryStepStatus.Next when !string.IsNullOrEmpty(_data.Warning) => Palettes.Status.Warning,
            SurgeryStepStatus.Next => theme.Highlight.Base,
            SurgeryStepStatus.Complete => Palettes.Status.Good.WithAlpha(0.7f),
            _ => null,
        };

        if (outline is { } color)
        {
            _box.Texture = _borderedTexture;
            _box.Modulate = color;
        }
        else
        {
            _box.Texture = _texture;
            _box.Modulate = theme.Buttons.DisabledElement;
        }

        _box.Draw(handle, PixelSizeBox, UIScale);

        if (status != SurgeryStepStatus.Active)
            return;

        var fraction = _data.ActiveDuration > TimeSpan.Zero
            ? Math.Clamp((float) ((_timing.CurTime - _data.ActiveStart) / _data.ActiveDuration), 0f, 1f)
            : 1f;

        // A bar in the bottom padding, clear of the cut corner and the icon.
        var left = Padding * UIScale;
        var width = PixelWidth - left * 2;
        var top = PixelHeight - (Padding - 2f) * UIScale;
        handle.DrawRect(new UIBox2(left, top, left + width, top + 3f * UIScale), theme.Highlight.Element);
        handle.DrawRect(new UIBox2(left, top, left + width * fraction, top + 3f * UIScale), Palettes.Status.Good);
    }
}
