using Content.Client.Stylesheets;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client._Arcane.Medical.Surgery;

public enum SurgeryOperationStatus : byte
{
    Available,
    Started,
    Closing,
    Completed,
}

/// <summary>
/// An operation in the chart; its progress counts the steps of the surgeries it requires as well.
/// </summary>
public sealed record SurgeryOperationEntry(
    EntProtoId Id,
    string Name,
    SurgeryOperationStatus Status,
    int Done,
    int Total);

[GenerateTypedNameReferences]
public sealed partial class SurgeryOperationRow : BoxContainer
{
    private readonly List<SurgeryStepIcon> _icons = new();

    public event Action? OnHeaderPressed;

    public SurgeryOperationRow()
    {
        RobustXamlLoader.Load(this);
        Header.OnPressed += _ => OnHeaderPressed?.Invoke();
    }

    /// <summary>
    /// Shows the operation header, and for the open operation the steps of its whole requirement chain.
    /// The header stays pressed while the operation is the surgeon's plan.
    /// </summary>
    public void Set(SurgeryOperationEntry entry,
        IReadOnlyList<SurgeryStepData> steps,
        bool planned,
        Func<EntityUid, Texture?> getIcon)
    {
        Header.Pressed = planned;
        Stripe.PanelOverride = new StyleBoxFlat(GetStatusColor(entry.Status));
        ArrowLabel.Text = steps.Count > 0 ? "▼" : "▶";

        NameLabel.Text = entry.Name;
        NameLabel.SetOnlyStyleClass(entry.Status == SurgeryOperationStatus.Completed
            ? StyleClass.LabelWeak
            : StyleClass.LabelKeyText);

        if (entry.Status == SurgeryOperationStatus.Completed)
        {
            StatusLabel.Text = "✓";
            StatusLabel.SetOnlyStyleClass(StyleClass.StatusGood);
        }
        else if (entry.Done > 0)
        {
            StatusLabel.Text = $"{entry.Done}/{entry.Total}";
            StatusLabel.SetOnlyStyleClass(StyleClass.StatusWarning);
        }
        else
        {
            StatusLabel.Text = string.Empty;
        }

        // Icons are reused while the chain keeps its length, so progress does not reset hover or tooltips.
        if (_icons.Count != steps.Count)
            BuildSteps(steps.Count);

        for (var i = 0; i < steps.Count; i++)
        {
            _icons[i].Set(steps[i], getIcon(steps[i].StepEnt));
        }
    }

    private void BuildSteps(int count)
    {
        Steps.DisposeAllChildren();
        _icons.Clear();
        Steps.Visible = count > 0;
        if (count == 0)
            return;

        var chain = new WrapContainer { SeparationOverride = 4, CrossSeparationOverride = 4 };
        for (var i = 0; i < count; i++)
        {
            if (i > 0)
            {
                chain.AddChild(new Label
                {
                    Text = "→",
                    VerticalAlignment = VAlignment.Center,
                    StyleClasses = { StyleClass.LabelWeak },
                });
            }

            var icon = new SurgeryStepIcon();
            _icons.Add(icon);
            chain.AddChild(icon);
        }

        Steps.AddChild(chain);
    }

    private static Color GetStatusColor(SurgeryOperationStatus status)
    {
        return status switch
        {
            SurgeryOperationStatus.Started => Color.FromHex("#E0A93F"),
            SurgeryOperationStatus.Available => Color.FromHex("#5FBF6A"),
            SurgeryOperationStatus.Closing => Color.FromHex("#4FA3E0"),
            _ => Color.FromHex("#3E6B47"),
        };
    }
}
