using System.Numerics;
using Content.Client.Stylesheets;
using Robust.Client.AutoGenerated;
using Robust.Client.Input;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Input;
using Robust.Shared.Prototypes;
using Robust.Shared.Timing;

namespace Content.Client._Arcane.Medical.Surgery;

public enum SurgeryOperationGroup : byte
{
    Started,
    Available,
    NeedsPreparation,
    Closing,
    Completed,
}

public readonly record struct SurgeryOperationEntry(
    EntProtoId Id,
    string Name,
    SurgeryOperationGroup Group,
    int Done,
    int Total,
    string? Hint);

[GenerateTypedNameReferences]
public sealed partial class SurgeryOperationsPopup : Popup
{
    [Dependency] private readonly IInputManager _input = default!;

    public event Action<EntProtoId>? OnOperationPressed;

    private Vector2? _dragOffset;
    private Vector2? _movedOrigin;

    public SurgeryOperationsPopup()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        DragHandle.OnKeyBindDown += args =>
        {
            if (args.Function != EngineKeyFunctions.UIClick)
                return;

            _dragOffset = args.PointerLocation.Position / UIScale - GlobalPosition;
            args.Handle();
        };
        DragHandle.OnKeyBindUp += args =>
        {
            if (args.Function == EngineKeyFunctions.UIClick)
                _dragOffset = null;
        };
        // Escape and outside clicks hide the popup without calling Close().
        OnPopupHide += () => _dragOffset = null;
    }

    /// <summary>
    /// Opens next to the anchor, or where the user last dragged the popup.
    /// </summary>
    public void OpenNear(UIBox2 anchor)
    {
        if (_movedOrigin is { } origin)
        {
            Open(UIBox2.FromDimensions(origin, Vector2.Zero));
            return;
        }

        Open(UIBox2.FromDimensions(new Vector2(anchor.Right + 6, anchor.Top), Vector2.Zero),
            new Vector2(anchor.Left - 6, anchor.Top));
    }

    // The handle keeps mouse focus while the button is held, so polling the cursor follows fast drags off the handle.
    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        if (_dragOffset is not { } offset)
            return;

        var origin = _input.MouseScreenPosition.Position / UIScale - offset;
        // A click on the handle without moving must not pin the popup in place.
        if (_movedOrigin == origin || origin.EqualsApprox(GlobalPosition))
            return;

        _movedOrigin = origin;
        PopupContainer.SetAltOrigin(this, null);
        PopupContainer.SetPopupOrigin(this, origin);
    }

    public void Populate(string title, IReadOnlyList<SurgeryOperationEntry> entries, EntProtoId? selected)
    {
        TitleLabel.Text = title;
        Operations.DisposeAllChildren();
        EmptyLabel.Visible = entries.Count == 0;

        SurgeryOperationGroup? group = null;
        foreach (var entry in entries)
        {
            if (entry.Group != group)
            {
                group = entry.Group;
                Operations.AddChild(new Label
                {
                    Text = Loc.GetString($"surgery-ui-group-{GetGroupId(entry.Group)}"),
                    StyleClasses = { StyleClass.LabelSubText },
                    Margin = new Thickness(4, 6, 0, 0),
                });
            }

            var button = new SurgeryOperationButton();
            button.Set(entry, entry.Id == selected);
            button.OnPressed += _ => OnOperationPressed?.Invoke(entry.Id);
            Operations.AddChild(button);
        }
    }

    private static string GetGroupId(SurgeryOperationGroup group)
    {
        return group switch
        {
            SurgeryOperationGroup.Started => "started",
            SurgeryOperationGroup.Available => "available",
            SurgeryOperationGroup.NeedsPreparation => "needs-preparation",
            SurgeryOperationGroup.Closing => "closing",
            _ => "completed",
        };
    }
}
