using Content.Client.Stylesheets;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Arcane.Medical.Surgery;

[GenerateTypedNameReferences]
public sealed partial class SurgeryOperationButton : Button
{
    public SurgeryOperationButton()
    {
        RobustXamlLoader.Load(this);
    }

    public void Set(SurgeryOperationEntry entry, bool selected)
    {
        Pressed = selected;
        Stripe.PanelOverride = new StyleBoxFlat(GetGroupColor(entry.Group));

        NameLabel.Text = entry.Name;
        NameLabel.SetOnlyStyleClass(entry.Group is SurgeryOperationGroup.NeedsPreparation or SurgeryOperationGroup.Completed
            ? StyleClass.LabelWeak
            : StyleClass.LabelKeyText);

        HintLabel.Text = entry.Hint ?? string.Empty;
        HintLabel.Visible = entry.Hint != null;

        if (entry.Group == SurgeryOperationGroup.Completed)
        {
            StatusLabel.Text = "✓";
            StatusLabel.SetOnlyStyleClass(StyleClass.StatusGood);
        }
        else if (entry.Done > 0 && entry.Group != SurgeryOperationGroup.NeedsPreparation)
        {
            StatusLabel.Text = $"{entry.Done}/{entry.Total}";
            StatusLabel.SetOnlyStyleClass(StyleClass.StatusWarning);
        }
        else
        {
            StatusLabel.Text = string.Empty;
        }
    }

    private static Color GetGroupColor(SurgeryOperationGroup group)
    {
        return group switch
        {
            SurgeryOperationGroup.Started => Color.FromHex("#E0A93F"),
            SurgeryOperationGroup.Available => Color.FromHex("#5FBF6A"),
            SurgeryOperationGroup.Closing => Color.FromHex("#4FA3E0"),
            SurgeryOperationGroup.Completed => Color.FromHex("#3E6B47"),
            _ => Color.FromHex("#55555F"),
        };
    }
}
