- type: technology
  id: BasicArms
  name: research-technology-basic-arms-name
  description: research-technology-basic-arms-desc
  icon:
    sprite: Objects/Weapons/Guns/Ammunition/Casings/shotgun_shell.rsi
    state: beanbag
  discipline: Security
  tier: 1
  startingTechnology: true
  pointCosts:
  - type: General
    amount: 500
  recipeUnlocks:
  - MagazineShotgunBeanbag
  - BoxBeanbag
  - MagazineBoxShotgunBeanbagHighCaliber
  - ModularReceiver
  - BoxLethalshot
  - BoxShotgunSlug
  - MagazineBoxMagnum
  - MagazineBoxPistol
  - MagazineBoxRifle
  - MagazineBoxRifle762
  - MagazineRifle762
  - MagazineRifle762Empty
  - MagazinePistol
  - MagazinePistolEmpty
  - MagazinePistolSubMachineGun
  - MagazinePistolSubMachineGunEmpty
  - MagazinePistolSubMachineGunTopMounted
  - MagazinePistolSubMachineGunTopMountedEmpty
  - MagazineRifle
  - MagazineRifleEmpty
  - MagazineShotgun
  - MagazineShotgunEmpty
  - MagazineShotgunSlug
  - SpeedLoaderMagnum
  - SpeedLoaderMagnumEmpty
  - MagazineBoxShotgunHighCaliber
  - MagazineBoxShotgunSlugHighCaliber
  - MagazineBoxShotgunPracticeHighCaliber
  - MagazineShotgunLeverRifleEmpty
  - BoxShotgunPractice
  - MagazineBoxMagnumPractice
  - MagazineBoxPistolPractice
  - MagazineBoxRiflePractice
  - MagazineBoxRifle762Practice
  - WeaponDisablerPractice
  - WeaponLaserCarbinePractice
  - MagazineLightRiflePractice
  - MagazineRiflePractice
  - MagazineRifle762Practice
  - MagazinePistolPractice
  - SpeedLoaderMagnumPractice
  - MagazinePistolSubMachineGunPractice
  position: 0,0

- type: technology
  id: SecurityEquipment
  name: research-technology-security-equipment-name
  description: research-technology-security-equipment-desc
  icon:
    sprite: Objects/Tools/seclite.rsi
    state: seclite
  discipline: Security
  tier: 1
  announceChannels:
  - Security
  pointCosts:
  - type: General
    amount: 2500
  technologyPrerequisites:
  - BasicArms
  recipeUnlocks:
  - SurveillanceWirelessCameraBodySecurity
  - ContrabandDetectorCircuitboard
  - CriminalRecordsComputerCircuitboard
#  - WeaponEnergyTurretSecurityMachineCircuitboard # Arcane-Edit: Removed
  - PepperSpray
  - Zipties
  - FlashlightSeclite
  - ClothingBackpackElectropack
  - ClothingAggressionInhibitor # Arcane
#  - PortableFlasherMachineCircuitboard # Arcane-Edit: Removed
  - ForensicPad
  - TargetClown
  - TargetHuman
  - TargetSyndicate
  - WeaponFlareGunSecurity
  - Flash
  # Arcane-Edit-Start: Removed
#  - Stunbaton
#  - CombatKnife
#  - RiotShield
#  - GrenadeFlashBang
#  - SecHypo
#  - PolymerBaton
#  - SpearTelescopic
  # Arcane-Edit-End
  - PinpointerSecSquad # Arcane-Edit
  position: 0,-1 # Arcane-Edit

- type: technology
  id: CombatHUD
  name: research-technology-combat-hud-name
  description: research-technology-combat-hud-desc
  icon:
    sprite: _White/Clothing/Eyes/Goggles/thermal.rsi
    state: icon
  discipline: Security
  tier: 4
  announceChannels:
  - Security
  pointCosts:
  - type: General
    amount: 12500 # Arcane-Edit: 17500 > 12500
  technologyPrerequisites:
  - BeamWeapons
#  - AnomalyShells # Arcane-Edit: Removed
  - NightVision
  recipeUnlocks:
  - ClothingEyesThermalVisionGoggles
  position: 3,-4 # Arcane-Edit

- type: technology
  id: RiotSuppression
  name: research-technology-riot-suppression-name
  description: research-technology-riot-suppression-desc
  icon:
    sprite: _Goobstation/Objects/Weapons/Throwable/energy_bola.rsi
    state: icon
  discipline: Security
  tier: 2
  announceChannels:
  - Security
  pointCosts:
  - type: General
    amount: 5000
  technologyPrerequisites:
  - SecurityEquipment
  recipeUnlocks:
  - TelescopicShield
  - RiotBulletShield
  - Handcuffs
  - BolaEnergy
  - Truncheon
  - ClothingMaskMuzzleSecure
  - ClothingMaskMuzzleShock
  - WeaponDisabler
  # Arcane-Edit-Start
  - Stunbaton
  - PolymerBaton
  - RiotShield
  - GrenadeFlashBang
  - PortableFlasherMachineCircuitboard
  - SecHypo
  - CombatKnife
  - SpearTelescopic
  # Arcane-Edit-End
#  - WeaponDisablerSMG # Arcane-Edit: Removed
  position: 0,-2 # Arcane-Edit

- type: technology
  id: Explosives
  name: research-technology-explosives-name
  description: research-technology-explosives-desc
  icon:
    sprite: Objects/Weapons/Grenades/smoke.rsi
    state: icon
  discipline: Security
  tier: 3
  announceChannels:
  - Security
  - Medical
  pointCosts:
  - type: General
    amount: 7500
  technologyPrerequisites:
  - RiotSuppression
  requiredExperiments:
  - OrdnanceExplosiveLowyieldbomb
  recipeUnlocks:
  - ModularGrenade
  - SmokeGrenade
  - FlashPayload
  - ChemicalPayload
  - ShrapnelPayload
  # Arcane-Start
  - GrenadeBlast
  - GrenadeEMP
  - GrenadeFlash
  - MagazineGrenadeEmpty
  # Arcane-End
  position: -1,-3 # Arcane-Edit

- type: technology
  id: ExoticAmmo
  name: research-technology-exotic-ammo-name
  description: research-technology-exotic-ammo-desc
  icon:
    sprite: Objects/Weapons/Guns/Ammunition/Magazine/Rifle/rifle_mag.rsi
    state: base
  discipline: Security
  tier: 4
  announceChannels:
  - Security
  pointCosts:
  # Arcane-start
  - type: General
    amount: 17500 # Arcane-Edit: 15000 > 17500
  - type: Experimental
    amount: 50
  # Arcane-end
  technologyPrerequisites:
  - Explosives
  discountExperiments:
  - OrdnanceExplosiveHighyieldbomb
  discountExperimentCosts:
    OrdnanceExplosiveHighyieldbomb: 10000
  recipeUnlocks:
  # Incendiary
  - BoxShotgunIncendiary
  - MagazineRifleIncendiary
  - MagazinePistolIncendiary
  - MagazinePistolSubMachineGunIncendiary
  - MagazineBoxShotgunIncendiaryHighCaliber
  - SpeedLoaderMagnumIncendiary
  - MagazineShotgunIncendiary
  - MagazineBoxPistolIncendiary
  - MagazineBoxMagnumIncendiary
  - MagazineBoxRifle762Incendiary
  - MagazineRifle762Incendiary
  - MagazineBoxRifleIncendiary
  # Arcane-Edit-Start: Removed
#  # Uranium
#  - MagazineRifleUranium
#  - MagazinePistolUranium
#  - MagazinePistolSubMachineGunUranium
#  - SpeedLoaderMagnumUranium
#  - MagazineBoxPistolUranium
#  - MagazineBoxMagnumUranium
#  - MagazineBoxRifle762Uranium
#  - MagazineRifle762Uranium
#  - MagazineBoxRifleUranium
#  - BoxShotgunUranium
#  - MagazineBoxShotgunUraniumHighCaliber
  # Arcane-Edit-End
  # Tranquilizer
  - BoxShellTranquilizer
  # Shuttle
  # Arcane-Edit-Start: Removed
#  - GrenadeBlast
#  - GrenadeEMP
#  - GrenadeFlash
#  - MagazineGrenadeEmpty
  # Arcane-Edit-End
  - PowerCageMedium
  - PowerCageSmall
  - PowerCageHigh
  # Arcane-Edit-Start: Removed
#  # Other
#  - EnergyMagRifleDisabler
#  - EnergyMagRifleLethal
#  - MagazineSmart
#  - PowerCellIRRevolver
#  - PowerCellIRSMG
#  - PowerCellIonSMG
#  - PowerCellIRSniper
#  - MilitaryPowerCellLMG
#  - PowerCellBluespaceRevolver
#  - PowerCellBluespaceSMG
#  - PowerCellBluespaceSniper
#  - MilitaryPowerCellBluespaceLMG
  # Arcane-Edit-End
  position: -2,-4 # Arcane-Edit

# Arcane-Start
- type: technology
  id: UraniumAmmo
  name: research-technology-uranium-ammo-name
  description: research-technology-uranium-ammo-desc
  icon:
    sprite: Objects/Materials/ore.rsi
    state: uranium
  discipline: Security
  tier: 5
  announceChannels:
  - Security
  pointCosts:
  - type: General
    amount: 22500
  - type: Experimental
    amount: 50
  technologyPrerequisites:
  - ExoticAmmo
  recipeUnlocks:
  - MagazineRifleUranium
  - MagazinePistolUranium
  - MagazinePistolSubMachineGunUranium
  - SpeedLoaderMagnumUranium
  - MagazineBoxPistolUranium
  - MagazineBoxMagnumUranium
  - MagazineBoxRifle762Uranium
  - MagazineRifle762Uranium
  - MagazineBoxRifleUranium
  - BoxShotgunUranium
  - MagazineBoxShotgunUraniumHighCaliber
  position: -3,-5
# Arcane-End

- type: technology
  id: ElectricWeapons
  name: research-technology-electric-weapons-name
  description: research-technology-electric-weapons-desc
  icon:
    sprite: _Goobstation/Objects/Weapons/Guns/Battery/ion_rifle.rsi
    state: base
  discipline: Security
  tier: 3
  announceChannels:
  - Security
  pointCosts:
  - type: General
    amount: 10000 # Arcane-Edit: 15000 > 10000
  technologyPrerequisites:
  - RiotSuppression
  recipeUnlocks:
  - WeaponEnergyIonRifle
  - PowerCellIonRevolver
  - EnergyMagRifleIon
  - PowerCellIonSniper
  - WeaponTemperatureGun
  # Arcane-Start
  - PowerCellIonSMG
  - WeaponDisablerSMG
  - WeaponEnergyTurretSecurityMachineCircuitboard
  # Arcane-End
  position: 2,-3 # Arcane-Edit

- type: technology
  id: BeamWeapons
  name: research-technology-beam-weapons-name
  description: research-technology-beam-weapons-desc
  icon:
    sprite: Objects/Weapons/Guns/Battery/xray.rsi
    state: icon
  discipline: Security
  tier: 4
  announceChannels:
  - Security
  pointCosts:
  - type: General
    amount: 10000
  technologyPrerequisites:
  - ElectricWeapons
  recipeUnlocks:
  - WeaponXrayCannon
  - HoloprojectorSecurityAdvanced
  - PowerCellXrayRevolver
  - PowerCellXraySMG
  - PowerCellXraySniper
  - AntiMindControlDevice
  position: 2,-4 # Arcane-Edit

- type: technology
  id: WeaponizedLaserManipulation
  name: research-technology-weaponized-laser-manipulation
  description: research-technology-weaponized-laser-manipulation-desc
  icon:
    sprite: Objects/Weapons/Guns/Battery/laser_cannon.rsi
    state: base
  discipline: Security
  tier: 3 # Arcane-Edit
  announceChannels:
  - Security
  pointCosts:
  - type: General
    amount: 10000 # Arcane-Edit: 15000 > 10000
  technologyPrerequisites:
  - RiotSuppression # Arcane-Edit
  recipeUnlocks:
  - WeaponLaserCarbine
  - WeaponLaserCannon
  # Arcane-Start
  - WeaponLaserCellRevolver
  - WeaponLaserCellSMG
  - PowerCellIRRevolver
  - PowerCellIRSMG
  - PortableRecharger
  # Arcane-End
  position: 1,-3 # Arcane-Edit

- type: technology
  id: PortableMicrofusionWeaponry
  name: research-technology-portable-microfusion-weaponry
  description: research-technology-portable-microfusion-weaponry-desc
  icon:
    sprite: Objects/Weapons/Guns/Battery/advancedlasergun.rsi
    state: base
  discipline: Security
  tier: 5 # Arcane-Edit
  announceChannels:
  - Security
  pointCosts:
  # Arcane-start
  - type: General
    amount: 30000 # Arcane-Edit: 40000 > 30000
  - type: Experimental
    amount: 50
  # Arcane-end
  technologyPrerequisites:
  - BeamWeapons
  - WeaponizedLaserManipulation
  - PartsBluespace
  recipeUnlocks:
  - WeaponAdvancedLaser
  - WeaponEnergyRifle
  # Arcane-Edit-Start: Removed
#  - WeaponLaserCellRevolver
#  - WeaponLaserCellSMG
  # Arcane-Edit-End
  - WeaponLaserCellSniper
  - Terminus
#  - PortableRecharger # Arcane-Edit: Removed
  - EnergyMagRifleOverchargeLethal
  - PowerCellOverchargedRevolver
  - PowerCellOverchargedSMG
  - PowerCellOverchargedSniper
  # Arcane-Start
  - EnergyMagRifleDisabler
  - EnergyMagRifleLethal
  - PowerCellIRSniper
  - PowerCellBluespaceRevolver
  - PowerCellBluespaceSMG
  - PowerCellBluespaceSniper
  # Arcane-End
  position: 1,-5 # Arcane-Edit

- type: technology
  id: SmartWeaponry
  name: research-technology-smart-weaponry
  description: research-technology-smart-weaponry-desc
  icon:
    sprite: _Goobstation/Objects/Weapons/Guns/SMGs/smartgun.rsi
    state: base
  discipline: Security
  tier: 5 # Arcane-Edit
  announceChannels:
  - Security
  pointCosts:
  - type: General
    amount: 20000
  technologyPrerequisites:
  # Arcane-Edit-Start
  - ExoticAmmo
  - PartsBluespace
  # Arcane-Edit-End
  recipeUnlocks:
  - WeaponSubMachineSmart
  - MagazineSmart # Arcane
  position: -2,-5 # Arcane-Edit

- type: technology
  id: HeavyWeaponry
  name: research-technology-heavy-weaponry
  description: research-technology-heavy-weaponry-desc
  icon:
    sprite: _Goobstation/Clothing/Back/Backpacks/lmg_backpack.rsi
    state: icon
  discipline: Security
  tier: 5 # Arcane-Edit
  announceChannels:
  - Security
  pointCosts:
  - type: General
    amount: 17000 # Arcane-Edit: 20000 > 17000
  technologyPrerequisites:
  - PortableMicrofusionWeaponry # Arcane-Edit
  recipeUnlocks:
  - ClothingBackpackLMGBattery
  # Arcane-Start
  - MilitaryPowerCellLMG
  - MilitaryPowerCellBluespaceLMG
  # Arcane-End
  position: 1,-6 # Arcane-Edit

- type: technology
  id: EnergyBarriers
  name: research-technology-energy-barriers
  description: research-technology-energy-barriers-desc
  icon:
    sprite: _Orion/Objects/Tools/EnergyDome/reinhardt.rsi
    state: icon
  discipline: Security
  tier: 4 # Arcane-Edit
  announceChannels:
  - Security
  pointCosts:
  - type: General
    amount: 10000 # Arcane-Edit: 12000 > 10000
  technologyPrerequisites:
  # Arcane-Edit-Start
  - RiotSuppression
  - ElectricWeapons
  # Arcane-Edit-End
  recipeUnlocks:
  - EnergyDomeTurtle
  position: 0,-4 # Arcane-Edit
