// SPDX-License-Identifier: AGPL-3.0-or-later

using Content.Client._Arcane.Administration.UI.Bwoink;
using Content.Shared.Administration;
using Content.Shared.Administration.Logs;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;
using Robust.Shared.Utility;

namespace Content.Client.Administration.UI.Bwoink
{
    [GenerateTypedNameReferences]
    public sealed partial class BwoinkPanel : BoxContainer
    {
        private readonly Action<string> _messageSender;
        // Arcane-Edit-Start
        private static readonly TimeSpan HistoryRequestTimeout = TimeSpan.FromSeconds(10);
        private DateTime _historyRequestedAt = DateTime.MinValue;
        private AdminLogCursor? _nextHistoryCursor;
        private bool _historyLoaded;
        private readonly List<BwoinkHistoryMessage> _historyMessages = new();
        private readonly List<SharedBwoinkSystem.BwoinkTextMessage> _liveMessages = new();
        private int? _displayedRoundId;
        // Arcane-Edit-End

        public int Unread { get; private set; } = 0;
        public DateTime LastMessage { get; private set; } = DateTime.MinValue;
        private List<string> PeopleTyping { get; set; } = new();
        public event Action<string>? InputTextChanged;

        public BwoinkPanel(Action<string> messageSender)
        {
            RobustXamlLoader.Load(this);

            var msg = new FormattedMessage();
            msg.PushColor(Color.LightGray);
            msg.AddText(Loc.GetString("bwoink-system-messages-being-relayed-to-discord"));
            msg.Pop();
            RelayedToDiscordLabel.SetMessage(msg);

            _messageSender = messageSender;

            OnVisibilityChanged += c =>
            {
                if (c.Visible)
                    Unread = 0;
            };
            SenderLineEdit.OnTextEntered += Input_OnTextEntered;
            SenderLineEdit.OnTextChanged += Input_OnTextChanged;
            UpdateTypingIndicator();
        }

        private void Input_OnTextEntered(LineEdit.LineEditEventArgs args)
        {
            if (string.IsNullOrWhiteSpace(args.Text))
                return;

            _messageSender.Invoke(args.Text);
            SenderLineEdit.Clear();
        }

        private void Input_OnTextChanged(LineEdit.LineEditEventArgs args)
        {
            InputTextChanged?.Invoke(args.Text);
        }

        public void ReceiveLine(SharedBwoinkSystem.BwoinkTextMessage message)
        {
            if (!Visible)
                Unread++;

            if (!_historyLoaded)
                _liveMessages.Add(message);

            AddLine(message.SentAt, message.Text, message.RoundId);
        }

        // Arcane-start
        public bool TryBeginHistoryRequest(out AdminLogCursor? cursor)
        {
            cursor = _nextHistoryCursor;
            if (_historyLoaded || DateTime.UtcNow - _historyRequestedAt < HistoryRequestTimeout)
                return false;

            _historyRequestedAt = DateTime.UtcNow;
            return true;
        }

        public void ClearHistory()
        {
            TextOutput.Clear();
            LastMessage = DateTime.MinValue;
            _displayedRoundId = null;
        }

        public void ReceiveHistory(IEnumerable<BwoinkHistoryMessage> messages, bool append, AdminLogCursor? nextCursor, bool hasMore)
        {
            if (_historyLoaded)
                return;

            if (!append)
                _historyMessages.Clear();

            _historyMessages.AddRange(messages);
            RenderMessages();

            _historyRequestedAt = DateTime.MinValue;
            if (hasMore && nextCursor != null)
                _nextHistoryCursor = nextCursor;
            else
            {
                _historyLoaded = true;
                _liveMessages.Clear();
                _historyMessages.Clear();
            }
        }

        private void RenderMessages()
        {
            ClearHistory();
            var unmatchedLive = new List<SharedBwoinkSystem.BwoinkTextMessage>(_liveMessages);

            foreach (var message in _historyMessages)
            {
                // Saved admin logs are UTC even if the database does not preserve DateTime.Kind.
                var utcTime = DateTime.SpecifyKind(message.SentAt, DateTimeKind.Utc);
                AddLine(utcTime.ToLocalTime(), message.Text, message.RoundId);

                var duplicate = unmatchedLive.FindIndex(live =>
                    live.Text == message.Text &&
                    live.AdminOnly == message.AdminOnly &&
                    live.RoundId == message.RoundId &&
                    Math.Abs((live.SentAt.ToUniversalTime() - utcTime).TotalSeconds) < 5);
                if (duplicate >= 0)
                    unmatchedLive.RemoveAt(duplicate);
            }

            foreach (var message in unmatchedLive)
                AddLine(message.SentAt, message.Text, message.RoundId);
        }

        private void AddLine(DateTime sentAt, string text, int? roundId)
        {
            if (roundId is > 0 && _displayedRoundId != roundId)
            {
                var separator = new FormattedMessage();
                separator.AddMarkupOrThrow($"[bwoinkround={roundId}/]");
                TextOutput.AddMessage(separator, [typeof(BwoinkRoundSeparatorTag)]);
                _displayedRoundId = roundId;
            }

            var formatted = new FormattedMessage(1);
            formatted.AddMarkupOrThrow($"[color=gray]{sentAt.ToShortTimeString()}[/color] {text}");
            TextOutput.AddMessage(formatted);
            LastMessage = sentAt;
        }
        // Arcane-end

        private void UpdateTypingIndicator()
        {
            TypingIndicator.Visible = PeopleTyping.Count > 0; // Arcane

            var msg = new FormattedMessage();
            msg.PushColor(Color.LightGray);

            var text = PeopleTyping.Count == 0
                ? string.Empty
                : Loc.GetString("bwoink-system-typing-indicator",
                    ("players", string.Join(", ", PeopleTyping)),
                    ("count", PeopleTyping.Count));

            msg.AddText(text);
            msg.Pop();

            TypingIndicator.SetMessage(msg);
        }

        public void UpdatePlayerTyping(string name, bool typing)
        {
            if (typing)
            {
                if (PeopleTyping.Contains(name))
                    return;

                PeopleTyping.Add(name);
                Timer.Spawn(TimeSpan.FromSeconds(10), () =>
                {
                    if (Disposed)
                        return;

                    PeopleTyping.Remove(name);
                    UpdateTypingIndicator();
                });
            }
            else
            {
                PeopleTyping.Remove(name);
            }

            UpdateTypingIndicator();
        }

        protected override void Dispose(bool disposing)
        {
            base.Dispose(disposing);

            InputTextChanged = null;
        }
    }
}
